other players with same qr, review and let me know what to change
CMPUT301W23T47/Canary pull request #124
Opened 2023-03-22 02:46 UTC by mobashhirkhan

**Description**

**Required Items**
- [ ] Linked Issue: #XYZ
- Tests
- [ ] Manually tested
- [ ] Unit Tests Added
- Style
  - [ ] No Lint Errors
- UI
    - [ ] Picture of before/after UI (if applicable)

2023-03-27 03:45 UTC, MSNanda515 requested changes

2023-03-27 03:45 UTC, MSNanda515 commented on app/src/main/java/com/cmput301w23t47/canary/controller/OtherPlayerViewer.java
> +    public void otherPlayerWithSameQr(String qrHash){
You can put this code in the FirestorePlayerController. Also, try to modify the API so that the calling object can get the list of players. Try to understand other function calls for examples.

2023-03-27 03:45 UTC, MSNanda515 commented on app/src/main/java/com/cmput301w23t47/canary/controller/OtherPlayerViewer.java
Also, add a fragment that actually shows the list of players to the user. This code is just a part of the functionality that will be required to get that functionality completely. As the task says, I expect to see work where I click on the button to view other players and am directed to a page with a list of those other players.

2023-04-01 07:40 UTC, mobashhirkhan commented
on clicking "view other players" it shows the list of other players but the name is not visible for some reason. on clicking them, i encounter a null issue as well. please take a look and change whatever is needed, i cannot figure it out

2023-04-01 21:12 UTC, MSNanda515 approved these changes
Manually tested

2023-04-01 21:13 UTC, merged