Added QR Code View
CMPUT301W23T47/Canary pull request #74
Opened 2023-02-22 20:47 UTC by jugal2601

**Description**

**Required Items**
- [ ] Linked Issue: #48
- Tests
- [ ] Manually tested: No
- [ ] Unit Tests Added: None
- Style
  - [ ] No Lint Errors
- UI
    - [ ] Picture of before/after UI (if applicable)
-Notes: color combination can be changed later. The single "user_comment.xml" is going to be used for the list view for comments. Functionality and tests all to be added later.

    
![image](https://user-images.githubusercontent.com/80158330/220754599-d2305f9a-93f5-4ac8-b2b1-41239c9e5a5a.png)

2023-02-23 00:10 UTC, MSNanda515 requested changes

2023-02-23 00:10 UTC, MSNanda515 commented on app/src/main/java/com/cmput301w23t47/canary/view/fragment/QRCodeView.java
> +        }
We should display the contents from the QR code object rather than hardcoding the XML. You should add a function that updates all the fields in the XML based on the QR Code object passed

2023-02-23 00:10 UTC, MSNanda515 commented on app/src/main/java/com/cmput301w23t47/canary/view/fragment/QRCodeView.java
> +    public static QRCodeView newInstance(String param1, String param2) {
I think you should get the PlayerQrCode as argument.

2023-02-23 19:11 UTC, jugal2601 commented on app/src/main/java/com/cmput301w23t47/canary/view/fragment/QRCodeView.java
> +        }
I thought this was an implementation detail so I left it as is. No worries, I'll add a method to update the fields and push the changes

2023-02-24 02:46 UTC, MSNanda515 approved these changes

2023-02-24 02:46 UTC, merged